### ISSUE TITLE
Separation of rise/fall time

### ISSUE THREAD

**Issue by absalom-muc** [hideakitai/Debouncer#3]
For a long button press a second instance of Debouncer can be used. But then you have to wait "long" time before you can press the button a second time because of the identical rise/fall time. Therefore it would be helpful when rise/fall time could be separated. (follow-up from [this issue](https://github.com/hideakitai/Debouncer/issues/2))

**Comment by hideakitai** [comment]
@absalom-muc Supported in v0.2.6. Please try it!

**Comment by absalom-muc** [comment]
Thank you, I'll give it a try.

**Comment by absalom-muc** [comment]
Works perfect, appreciate your support!

(a minor hint : You could consider adding release notes in future to make it simpler for the user to see if a new relase was due to a bug fix or new feature)
